Repository kasuboski/mediaz, pull requests merged in 2025-07, with the labels that each got.

#54 Endpoint to get details for a movie given TMDB ID
  pkg/manager/manager.go
  pkg/manager/manager_test.go
  server/server.go
  server/server_test.go
Labels: enhancement, size:XL, lgtm

#55 Add tv show detail endpoint
  pkg/manager/manager.go
  pkg/manager/manager_test.go
  pkg/manager/metadata.go
  server/server.go
  server/server_test.go
Labels: enhancement, size:XL, lgtm

#56 Feature/continued and completed series state
  pkg/manager/metadata.go
  pkg/manager/series_reconcile.go
  pkg/manager/series_reconcile_test.go
  pkg/storage/mocks/mock_storage.go
  pkg/storage/sqlite/series.go
  pkg/storage/sqlite/series_test.go
  pkg/storage/storage.go
Labels: enhancement, size:XXL, lgtm

#58 Handle more title possibilities
  pkg/manager/release.go
  pkg/manager/release_test.go
Labels: enhancement, size:M, lgtm
