Repository kasuboski/mediaz, pull requests merged in 2025-09, with the labels that each got.

#70 Frontend: Shows
  docs/API.md
  frontend/src/components/media/MediaGrid.tsx
  frontend/src/lib/api.ts
  frontend/src/lib/queries.ts
  frontend/src/pages/Series.tsx
  frontend/src/pages/TVDetail.tsx
  pkg/manager/manager.go
  pkg/manager/manager_test.go
  pkg/manager/manager_types.go
  pkg/manager/tv_detail_test.go
  pkg/storage/sqlite/series.go
  server/server.go
  server/server_test.go
Labels: bug, size:XXL, lgtm

#72 fix quality tables
  pkg/storage/sqlite/schema/defaults.sql
  pkg/storage/sqlite/schema/schema.sql
  pkg/storage/sqlite/sqlite.go
  pkg/storage/storage.go
Labels: bug, size:M, lgtm

#71 add mutex for writes to db
  pkg/storage/sqlite/series.go
  pkg/storage/sqlite/sqlite.go
Labels: bug, size:L, lgtm

#77 fix static file handling
  frontend/vite.config.ts
  server/server.go
Labels: bug, size:S, lgtm

#78 Bugfix/frontend api url
  frontend/src/lib/api.ts
  frontend/vite.config.ts
Labels: bug, size:M, lgtm

#81 75 continuing series missing series results in invalid state
  pkg/library/api.go
  pkg/library/episode_test.go
  pkg/library/library_test.go
  pkg/manager/series_reconcile.go
  pkg/storage/storage.go
Labels: bug, size:L, lgtm

#82 fix relationship between series and season metadata
  pkg/manager/manager.go
  pkg/manager/metadata.go
  pkg/manager/series_reconcile.go
  pkg/manager/series_reconcile_test.go
  pkg/storage/mocks/mock_storage.go
  pkg/storage/sqlite/schema/gen/model/season_metadata.go
  pkg/storage/sqlite/schema/gen/table/season_metadata.go
  pkg/storage/sqlite/schema/schema.sql
  pkg/storage/sqlite/series.go
  pkg/storage/storage.go
Labels: enhancement, size:L, lgtm

#85 Bugfix/metadata linking
  README.md
  cmd/library.go
  cmd/schema.go
  pkg/manager/manager.go
  pkg/manager/metadata.go
  pkg/manager/metadata_test.go
  pkg/manager/series_index.go
  pkg/manager/series_reconcile.go
  pkg/manager/series_reconcile_test.go
  pkg/storage/sqlite/schema/gen/model/episode_metadata.go
  pkg/storage/sqlite/schema/gen/model/season_metadata.go
  pkg/storage/sqlite/schema/gen/table/episode_metadata.go
  pkg/storage/sqlite/schema/gen/table/season_metadata.go
  pkg/storage/sqlite/schema/schema.sql
  pkg/tmdb/tmdb.go
Labels: bug, size:XXL, lgtm
